### ISSUE TITLE
Issue with New Clients Widget

### ISSUE THREAD

**Issue by dcoobs** [munkireport/machine#5]
I'm seeing errors with the new client widget after upgrading to v3.0.

```
Fatal error: Uncaught Error: Call to undefined method View::viewWidget() in /var/storage/munkireport-php-5.2.0/vendor/munkireport/machine/views/new_clients_widget.php:3 Stack trace: #0 /var/storage/munkireport-php-5.2.0/system/kissmvc_core.php(292): include() #1 /var/storage/munkireport-php-5.2.0/app/lib/munkireport/Widgets.php(82): KISS_View->view('new_clients_wid...', Array, '/var/storage/mu...') #2 /var/storage/munkireport-php-5.2.0/app/views/dashboard/dashboard.php(17): munkireport\lib\Widgets->view(Object(View), 'new_clients', Array) #3 /var/storage/munkireport-php-5.2.0/system/kissmvc_core.php(292): include('/var/storage/mu...') #4 /var/storage/munkireport-php-5.2.0/app/lib/munkireport/Dashboard.php(115): KISS_View->view('dashboard/dashb...', Array) #5 /var/storage/munkireport-php-5.2.0/app/controllers/show.php(38): munkireport\lib\Dashboard->render('default') #6 /var/storage/munkireport-php-5.2.0/system/kissmvc_core.php(84): munkireport\controller\show->dashboard('default') #7 /var/storage/munkireport-php-5.2.0/sys in /var/storage/munkireport-php-5.2.0/vendor/munkireport/machine/views/new_clients_widget.php on line 3
```

**Comment by bochoven** [comment]
3.0 needs a newer version of MunkiReport. Stick to 2.x
